project:
  type: website
  output-dir: ../WeathervsOffense.github.io

website:
  description: "data and sports and stuff"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Duke's Sports Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - minty
      - brand
    css: styles.css

editor: visual

